osx_image: xcode10.3
language: objective-c
install:
  - bundle install --gemfile=Example/Gemfile
  - bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Stagehand.xcworkspace -scheme "Stagehand Demo App" -sdk iphonesimulator12.4 ONLY_ACTIVE_ARCH=NO | xcpretty
  - bundle exec --gemfile=Example/Gemfile pod lib lint
