name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  pod-lint:
    name: Pod Lint
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Lint Stagehand Podspec
        run: bundle exec --gemfile=Example/Gemfile pod lib lint --verbose --fail-fast Stagehand.podspec
      - name: Lint StagehandTesting Podspec
        run: bundle exec --gemfile=Example/Gemfile pod lib lint --verbose --fail-fast --include-podspecs=Stagehand.podspec StagehandTesting.podspec
  spm:
    name: SPM Build
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Prepare Simulator Runtimes
        run: Scripts/github/prepare-simulators.sh ${{ matrix.platform }}
      - name: Build
        run: |
          swift build \
            --sdk "$(xcode-select -p)/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk" \
            --triple "arm64-apple-ios13.0"
